### ISSUE TITLE
[BUG] Ticketsystem reply is white

### ISSUE THREAD

**Issue by julianfegert** [Paymenter/Paymenter#467]
![tempImage6NOZjW](https://github.com/Paymenter/Paymenter/assets/173612750/5a446552-5d80-49e6-ac42-d7af81432335)
the support agent's answers have a white background and white writing, which makes the answers difficult to read

**Comment by NOXITB** [comment]
You should use 

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]
 - Browser [e.g. chrome, safari]
 - Version [e.g. 22]

**Smartphone (please complete the following information):**
 - Device: [e.g. iPhone6]
 - OS: [e.g. iOS8.1]
 - Browser [e.g. stock browser, safari]
 - Version [e.g. 22]

**Additional context**
Add any other context about the problem here.
